version: 0.0
os: linux
files:
  - source: /devops-playground
    destination: /usr/local/bin/
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: root
